application: gigapan-mobile
version: 2011-06-19-1
runtime: python
api_version: 1


builtins:
- datastore_admin: on
- remote_api: on


handlers:
- url: /tasks/sync
  script: app.py
  login: admin

- url: /static
  static_dir: static

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /api/1/.*
  script: api-1.py

- url: /.*
  script: app.py
